In [2]:
import torch

In [6]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x+2
print(y)
z = y*y*2
#z = z.mean()
print(z)
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([-1.0640,  0.1493,  1.3110], requires_grad=True)
tensor([0.9360, 2.1493, 3.3110], grad_fn=<AddBackward0>)
tensor([ 1.7523,  9.2393, 21.9260], grad_fn=<MulBackward0>)
tensor([0.3744, 8.5973, 0.0132])
