In [2]:
import torch

tensor([[9.7251e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])


In [4]:
# empty tensor with on value
x = torch.rand(2, 3)
x

tensor([[0.9846, 0.5537, 0.0062],
        [0.4387, 0.6287, 0.5943]])

In [6]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [9]:
x = torch.empty(2, 3, dtype=torch.double)
print(x.size())

torch.Size([2, 3])


In [10]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.6605, 0.9254],
         [0.9974, 0.5127]]), tensor([[0.9757, 0.7276],
         [0.3335, 0.4007]]))

In [13]:
z = x + y
z

tensor([[1.6362, 1.6530],
        [1.3309, 0.9134]])

In [15]:
z = torch.add(x,y)
z

tensor([[1.6362, 1.6530],
        [1.3309, 0.9134]])

In [16]:
y.add_(x)
y

tensor([[1.6362, 1.6530],
        [1.3309, 0.9134]])

In [18]:
k = z*x
k

tensor([[1.0807, 1.5296],
        [1.3274, 0.4683]])

In [24]:
x = torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[2, 2].item())

tensor([[0.3778, 0.6771, 0.9516],
        [0.5563, 0.6309, 0.5901],
        [0.5779, 0.8609, 0.8236],
        [0.7043, 0.6525, 0.7016],
        [0.8215, 0.2754, 0.8783]])
tensor([0.3778, 0.5563, 0.5779, 0.7043, 0.8215])
tensor([0.5563, 0.6309, 0.5901])
0.8235822916030884


In [25]:
# reshaping
x = torch.rand(4,4)
print(x)
y = x.view(16) #num of elements is the same
print(y)

tensor([[0.6599, 0.7955, 0.4204, 0.3419],
        [0.7538, 0.1409, 0.6189, 0.9423],
        [0.4123, 0.1702, 0.8829, 0.2140],
        [0.5632, 0.7290, 0.3713, 0.2782]])
tensor([0.6599, 0.7955, 0.4204, 0.3419, 0.7538, 0.1409, 0.6189, 0.9423, 0.4123,
        0.1702, 0.8829, 0.2140, 0.5632, 0.7290, 0.3713, 0.2782])
