In [26]:
import numpy as np
import torch

In [5]:
np.arange(0, 0, 0.5, dtype=int)


array([], dtype=int64)

In [6]:
np.arange(0, 1, 0.5, dtype=int)

array([0, 0])

In [7]:
np.arange(0, 2, 0.5, dtype=int)

array([0, 0, 0, 0])

In [8]:
np.arange(0, 1, 1, dtype=int)

array([0])

In [9]:
np.arange(0, 5, 1, dtype=int)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(0, 2, 0.25, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [14]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])
y = x.view(dtype=np.int16, type=np.matrix)
print(y)

[[513]]


In [15]:
x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
xv = x.view(dtype=np.int8).reshape(-1,2)
print(xv)

[[1 2]
 [3 4]]


In [17]:
a = np.zeros((10, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
b = a.T
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
c = b.view()
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
c.shape = (20)

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

In [23]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [24]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
a = np.arange(6).reshape((-1, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [29]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [30]:
torch.unsqueeze(x, -1)

tensor([[1],
        [2],
        [3],
        [4]])

In [31]:
torch.unsqueeze(x, -2)

tensor([[1, 2, 3, 4]])